resolver: lts-12.5
packages:
- .

extra-deps:
- generic-lens-1.1.0.0
# - type-level-sets-0.8.7.0
# - papa-0.3.1
# - papa-base-0.3.1
# - papa-base-export-0.4
# - papa-base-implement-0.3.1
# - papa-bifunctors-0.3.1
# - papa-bifunctors-export-0.3.1
# - papa-bifunctors-implement-0.3.1
# - papa-lens-0.3.1
# - papa-lens-export-0.3.1
# - papa-lens-implement-0.3.1
# - papa-semigroupoids-0.3.1
# - papa-semigroupoids-export-0.3.1
# - papa-semigroupoids-implement-0.3.1
# - papa-x-0.3.1
# - papa-x-export-0.3.1
# - papa-x-implement-0.3.1
- digit-0.7
- parsers-megaparsec-0.1.0.1
